### ISSUE TITLE
Issue Displaying the 'Excel Upload' button (Odata V2)

### ISSUE THREAD

**Issue by rameshputta79** [marianfoo/ui5-cc-excelUpload#233]
Hello,
I am trying to implement the excel upload tool into my Odata V2 application. My app has 3 layers, for example
- Orders -> Line Items->Schedule Lines
Part of the implementation, I am trying to add 'Excel Upload' button to the list report header of my 3rd layer (Schedule Lines) using 'Guided Development' in BAS . But somehow the button would not show up there. 
what am I missing.

thanks

**Comment by marianfoo** [comment]
Hi Ramesh,
the button in a object page has nothing to do with the excel upload component.
Please seek support at the SAP Community:
https://answers.sap.com/index.html

If i understood your question wrong, please comment again.

Regards
