### ISSUE TITLE
Install old Versions

### ISSUE THREAD

**Issue by carlostarraf** [marianfoo/ui5-cc-excelUpload#239]
HI !

How i could install the old versions?

**Comment by marianfoo** [comment]
Hi Carlos,
just edit the version in your package.json.
Any reason why you would like to change it?

**Comment by carlostarraf** [comment]
Hi Marian, 

how are you ? i hope be fine.

I Dev a sequence of 5 apps and i like the version 11.03 on the first 2 apps.

in current version 17.5 i don't like some options because it's a bit hard for user to use. Perhaps in the download template there is a flag or option to create only mandatory fields without technical names.. it is much better for the user since for me, the idea is not to change the template too much, to make it as standardized as possible.

If you also have the option to enable / leave certain options visible or not, that would be cool too... so it adapts to each type of need.

complementing I tried to edit the version only in the package.json but it didn't work, it says that it doesn't find the files folder.


Once again congratulations on the project...!

![imagem_2023-06-02_111754426](https://github.com/marianfoo/ui5-cc-excelUpload/assets/92546147/2ee7030b-590e-4675-82cf-14e11ee52ed9)

![imagem_2023-06-02_111846409](https://github.com/marianfoo/ui5-cc-excelUpload/assets/92546147/653d0c2c-3162-4973-aa19-170defe3b756)

![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/92546147/3ba359c0-9b67-4a27-93de-5cb86eba95e7)

**Comment by marianfoo** [comment]
Hi Carlos,

with the newest version of 0.18.0 the options menu is hidden by default. Currently its more a feature do debug for myself.
I´ll reintroduce it later with a another options to decide as developer to show only specific options to the user.

To hide the technical names in the excel template you can use the option [fieldMatchType](https://marianfoo.github.io/ui5-cc-excelUpload/pages/Configuration/#fieldmatchtype) `label`.  
This will only show the labels in the excel file template.  

With the option [columns](https://marianfoo.github.io/ui5-cc-excelUpload/pages/Configuration/#columns) you can decide which specific colums should appear in the excel file template.

Does this help you?

**Comment by carlostarraf** [comment]
Hi Marian!

Excelente! It work changing property fieldMatchType, but dont work with columns .. he still create template with all fields.

I do updated to version 18.0.

![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/92546147/63f0340c-6d1e-49a7-9f2f-9cb6eede837d)

**Comment by marianfoo** [comment]
Unfortunately i can´t recreate the scenario you described.
Please show the complete code you initialize the excel component including all the options.
Also:
- what UI5 version
- what OData Version
- Fiori Elements or Freestyle

**Comment by carlostarraf** [comment]
Hi Marian!

Sorry for retard time to response...

> what UI5 version
   The only version i can see in manisfest.json is the minUI5Version 1.84.30
   
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/92546147/44499fb5-f9f8-4510-98f1-de4de94287c5)

> what OData Version

 V2

> Fiori Elements or Freestyle

I'm using RAP/Fiori Elements

**Comment by marianfoo** [comment]
> Please show the complete code you initialize the excel component including all the options.

Please add this information

**Comment by carlostarraf** [comment]
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/92546147/bd42a78c-d5e1-43ed-b3cd-98b1378ce7ff)
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/92546147/ecc05448-6747-46b2-9f24-2ad29a10b9dc)
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/92546147/54ea6f69-dad0-4ec9-a73e-0475140b344e)

thats help?

**Comment by carlostarraf** [comment]
Thank you so much Marian!!! now its worked!

I will update others.


apparently I was the one doing it wrong haha

**Comment by marianfoo** [comment]
Glad I could help 🙂
