### ISSUE TITLE
Excel Upload keep spinning with Odata V2 app

### ISSUE THREAD

**Issue by rameshputta79** [marianfoo/ui5-cc-excelUpload#246]
Hi, 
I developed a Odata V2 application using restful abap which has 3 levels.
I am trying to upload the data from the excel using your tool for the 3rd level. 

By following the steps in https://marianfoo.github.io/ui5-cc-excelUpload/pages/GettingStarted/
I was able to create 'excel Upload' button in the object page. 
but when I select the button, it just keep spinning. 

Below is my extension in the manifest.json 
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/cb031e98-a83e-4843-9946-e9fe39a5d9a4)

And here is the Object page controller
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/eec75e73-2e26-47a7-a188-9cfb5b0574eb)

Iam using the version - v0_18_0

Please let me know if I am missing something.

**Comment by rameshputta79** [comment]
Hi Marian,
below is the manifest.json
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/27d765ab-2566-4c1a-b8cc-d6a750e9c9ca)

And i do not see any error in the console.

**Comment by marianfoo** [comment]
Hi Ramesh,
i don´t see any error in the code and config.
If you don´t see any error here i can´t help you right now.
Please debug the code where the error is happening.

**Comment by rameshputta79** [comment]
Marian,
I just tried again and this time I get the following error
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/3ef3ff75-a436-4cd4-91b3-b2fd24ec5520)
View details->
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/41137253-46e3-402f-a250-6e59c3b6ca24)

**Comment by marianfoo** [comment]
is it possible to post the complete manifest.json?

**Comment by rameshputta79** [comment]
Sent it to you through the email.

**Comment by rameshputta79** [comment]
Ok, I would try that.
But as a workaround, I tried to put the button on the object page of 2nd level and that worked. 
But when I select the excel from the desktop and tried to upload , it gives me following error.
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/08c772c3-e5a2-490b-9616-70124f1e1da0)

**Comment by marianfoo** [comment]
i tried your setup to upload data on a sub object page, and it worked on my cap setup without any options.
I just can assume it works also on a sub sub object page

**Comment by carlostarraf** [comment]
Hello,

I had this error. In my case I needed to re-deploy my app because apparently it didn't upload the files correctly to the server.

Try too update structure of you application

ex. npm i

Maybe that helps.

**Comment by rameshputta79** [comment]
> i tried your setup to upload data on a sub object page, and it worked on my cap setup without any options. I just can assume it works also on a sub sub object page

Marian, did you mean you tried uploading from the object page of 2nd level ? Unfortunately , it does not work for me.

![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/9b723030-0979-486b-bc85-1459b2043f5a)
when I tried to debug the backend code, it fails here. 

![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/fcc1426e-2bfe-4b14-8b1c-705d416dd0c3)

**Comment by rameshputta79** [comment]
> Hello,
> 
> I had this error. In my case I needed to re-deploy my app because apparently it didn't upload the files correctly to the server.
> 
> Try too update structure of you application
> 
> ex. npm i
> 
> Maybe that helps.

Hello, thanks for the response. I did not deploy my app yet, I am still testing this from BAS using 'Application Preview'

**Comment by marianfoo** [comment]
> > i tried your setup to upload data on a sub object page, and it worked on my cap setup without any options. I just can assume it works also on a sub sub object page
> 
> Marian, did you mean you tried uploading from the object page of 2nd level ? Unfortunately , it does not work for me.

Yes, that worked for me.
As this is a backend error, it´s not much i can do.
As @carlostarraf confirmed, it´s an error in your application or backend structure.
I cant replicate the complete ABAP Backend.

**Comment by marianfoo** [comment]
I reread your comments.
The Excel component is looking for a table control in the same view.
You can explizitly set the table I'd, but it has to be at the same view.
Unfortunately I can't help you with this backend error, but, i would like to to know the requests the Fiori app is generating and those from the Excel upload component.
Please create a entry with Fiori Elements and try to create a entry with the Excel component.
I need to know the payload of both request. I can maybe better understand what kind of requests the backend is expecting.

**Comment by marianfoo** [comment]
> Marian, I just tried again and this time I get the following error ![image](https://user-images.githubusercontent.com/121116258/243795491-3ef3ff75-a436-4cd4-91b3-b2fd24ec5520.png) View details-> ![image](https://user-images.githubusercontent.com/121116258/243795597-41137253-46e3-402f-a250-6e59c3b6ca24.png)

For this error, please update to `0.19.0` and follow [this documentation](https://marianfoo.github.io/ui5-cc-excelUpload/pages/Troubleshooting/#activate-debug-mode-and-copy-error-messages) and attach the error log

**Comment by marianfoo** [comment]
> Marian, I just tried again and this time I get the following error ![image](https://user-images.githubusercontent.com/121116258/243795491-3ef3ff75-a436-4cd4-91b3-b2fd24ec5520.png) View details-> ![image](https://user-images.githubusercontent.com/121116258/243795597-41137253-46e3-402f-a250-6e59c3b6ca24.png)

Improved again with error Message, also, please update to `0.19.1` and see if there are other error messages

**Comment by rameshputta79** [comment]
thanks Marian, unfortunatly that didnt help. Clicking on the 'Excel Upload' just keep spinning.

**Comment by marianfoo** [comment]
Hi @rameshputta79 ,
then please follow this [documentation](https://marianfoo.github.io/ui5-cc-excelUpload/pages/Troubleshooting/#activate-debug-mode-and-copy-error-messages) and attach the error log.
Thanks

**Comment by marianfoo** [comment]
Hi @rameshputta79 
thanks for using my component.
Unfortunately with this information you gave me i can´t help you.
You´re welcome to comment again if you have more info, logs or erros.

Thanks
Marian

**Comment by rameshputta79** [comment]
ok, but what does it usually means when it keep spinning ? 
Its hard for me to send you any other information when it does not provide any information :)

**Comment by marianfoo** [comment]
> ok, but what does it usually means when it keep spinning ? Its hard for me to send you any other information when it does not provide any information :)

spinning means a error happened visible in the console or with in debug mode, as described in previous comments
