### ISSUE TITLE
Excel Upload wont work when deployed into cloud foundry.

### ISSUE THREAD

**Issue by rameshputta79** [marianfoo/ui5-cc-excelUpload#252]
Hi Marian,
I am re-opening this thread as I am having an issue.
The excel upload works fine when I do the 'Application preview' from BAS. But when I deploy my application to the cloud foundry, the excel upload button does not work. When I click on it, it spins forever without any backend error.

_Originally posted by @rameshputta79 in https://github.com/marianfoo/ui5-cc-excelUpload/issues/202#issuecomment-1581413165_

**Comment by marianfoo** [comment]
Please use the bug template.
Thanks
