### ISSUE TITLE
[Bug]: Excel Upload does not work when deployed it to cloud foundry.

### ISSUE THREAD

**Issue by rameshputta79** [marianfoo/ui5-cc-excelUpload#253]
### OData Version

OData V4

### Draft

Yes

### Scenario

Fiori Elements

### UI5 Excel Component

v0_18_0

### What happened?

I have Odata V4 application with draft.

The excel upload works fine when I do the 'Application preview' from BAS. But when I deploy my application to the cloud foundry, the excel upload button does not work. When I click on it, it spins forever without any backend error.

Is there any additional step I need to follow when we deploy it?

### Excel Component Init

```js
na
```

**Comment by marianfoo** [comment]
Also here, please update to `0.19.0` and follow [this documentation](https://marianfoo.github.io/ui5-cc-excelUpload/pages/Troubleshooting/#activate-debug-mode-and-copy-error-messages) and attach the error log

**Comment by marianfoo** [comment]
Hi @rameshputta79 
please provide more information as instructed above.
Otherwise i can´t help you and will close this issue.
Thanks!

**Comment by rameshputta79** [comment]
Yes, please feel free to close it as I do not have any other information available to provide.
