### ISSUE TITLE
Karma deprecated

### ISSUE THREAD

**Issue by marianfoo** [marianfoo/ui5-cc-excelUpload#262]
Just setup karma and then realized its deprecated 😣

https://github.com/karma-runner/karma#karma-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes

https://github.com/Leaflet/Leaflet/issues/8939

https://github.com/ArnaudBuchholz/training-ui5con18-opa/issues/15

https://github.com/SAP/openui5-sample-app/issues/199

**Comment by wridgeu** [comment]
Let's hope your efforts are not totally in vain. I also recently stumped upon the issue you mentioned. Looking forward for an update on this one.
